### ISSUE TITLE
此项目可能被他人访问，请注意言辞

### ISSUE THREAD

**Issue by Glease** [MCIndustrial2Bar/MCIC2BAR#1]
因为这是个公开项目，所以请注意言辞。

**Comment by 3TUSK** [comment]
~~这就是你不写进README的理由吗（雾）~~
Done by 3b9516c8cbbb118d003c6d1537fa503cf44d385f

**Comment by Glease** [comment]
这个本来是想提醒在issue里的问题……

**Comment by 3TUSK** [comment]
@Glease my cellphone is no-power... and here you go: https://github.com/MrGTout
