### ISSUE TITLE
如何处理爆吧时遗留的吧友的无实质性帮助的贴子

### ISSUE THREAD

**Issue by Glease** [MCIndustrial2Bar/MCIC2BAR#10]
前段时间爆吧带来了大量坟贴被挖和大量无意义主题贴，但同时吧友也发表了许多类似“怎么又被爆吧了”，“爆吧警告”等等不是水贴，但是没有实质性帮助的贴子，这类贴子数量不少，但又不好直接删除，故提请讨论。

**Comment by 3TUSK** [comment]
冷处理。

**Comment by GWYOG** [comment]
感觉最近贴吧帖子的质量不断在降低，如果能有一些高质量的讨论贴或者贴吧的“活动贴”，无论是爆吧贴或是这些吐槽贴自然也能很快沉了。(这样想来有些大新闻似乎也是件好事....)
话说举办一次评选贴吧10大最受欢迎的mod之类的活动怎么样?

**Comment by 3TUSK** [comment]
@GWYOG 想法不错，但是比较担心路人投票严重影响结果，以及玩家因为不了解xxmod而导致票数大规模集中在诸如ic2exp这样的mod上。

**Comment by Glease** [comment]
> 话说举办一次评选贴吧10大最受欢迎的mod之类的活动怎么样?

@GWYOG 

活动很好，不过总觉得平时似乎删过这样的贴子……啊，吧友应该不会说什么吧

> 但是比较担心路人投票严重影响结果，以及玩家因为不了解xxmod而导致票数大规模集中在诸如ic2exp这样的mod上。

@3TUSK 
- 路人？路人怎么影响？？
- 大规模集中是可以理解的吧……毕竟标题是10大**最受欢迎**的mod

其实另一种看起来可以接受的方式是接龙，大家的话凑成一个故事，比如[这个](http://forum.industrial-craft.net/index.php?page=Thread&threadID=6744)

**Comment by 3TUSK** [comment]
@Glease 
- “路人”是指random guy，在吧里活跃了没几天就离开的那种。这种人对于长远发展不太好——我的想法是这样的：现在多数玩家的信息来源不够广，所以任何人都可能会因为各种misunderstanding导致各种误解扩散，这个时候“路人”就比较可怕了
- 于是新MOD永无出头之日？

**Comment by Glease** [comment]
- 我不是很确定你说的这种情况会不会出现……
- 这种活动本来就不是为了推出新的mod的。对于新mod更合适的是_贴吧10大有趣但不知名的mod_之类的东西

**Comment by GWYOG** [comment]
@Glease 

> 活动很好，不过总觉得平时似乎删过这样的贴子……啊，吧友应该不会说什么吧

官方举办的和平常吧友水贴的肯定是不一样的，后者太随意了，永远不能代表贴吧。举办这类活动一定要有个比较详细的规则
- 担心路人的话，可以限制参与等级，设置个7级左右应该可以吧？
- 国内知名mod占据前几名应该是不可避免的，但评选的不是最有名的而是10(15)大受欢迎的mod，所以应该会好点，话说为什么我感觉IC2EXP不会是第一呢...
- 想要新mod也上榜的话，可以考虑分区，比如汉化区/未汉化区，1.7.10区/1.8.9区，新作区/旧作区，科技类/魔法类/冒险类等等
- 原始想法来自[这儿](http://tieba.baidu.com/p/4349729270)，可以适当参考，像是一些拉票的介绍/showcase帖如果能有人发，想必是很有益处的
- 如果要举办这类活动我觉得还是加上个xx年度比较好

**Comment by Ahrwing** [comment]
如果要举办的话，建议用冷门MOD。
既能防止预期的某些MOD排名靠前，又能增加冷门MOD的覆盖率。

**Comment by Glease** [comment]
贴吧相对和谐，这个贴子暂时看来是没有必要了。
