### ISSUE TITLE
举报用户什么的可以发在这吧

### ISSUE THREAD

**Issue by Lead007** [MCIndustrial2Bar/MCIC2BAR#16]
举报@神之mmm大大 之前就一直只发一堆毫无意义的催更什么的，完全没进行过任何有意义讨论，现在又开始乱打封坟线，非常烦，希望你们考察一下。

**Comment by MrGTout** [comment]
这家伙啊，get√

**Comment by KaedeLen** [comment]
楼上那个是不是在我帖子开车那个→_→

**Comment by 3TUSK** [comment]
@elctove 你楼上是吧务。

**Comment by Glease** [comment]
已处理。话说以后@MrGTout 处理好issue以后记得关掉
