### ISSUE TITLE
Request a thorough removal of meaningless spam

### ISSUE THREAD

**Issue by 3TUSK** [MCIndustrial2Bar/MCIC2BAR#17]
如题，关于MOD分类讨论的水贴太多了...
顺手联动 Ahrwing/mcmod#158, Ahrwing/mcmod#204, Ahrwing/mcmod#226, 因为，百科也需要一个统一的MOD分类标准。

**Comment by 3TUSK** [comment]
~~@Glease @Ahrwing @MrGTout @Grazhangjunde ~~
~~你要的issue~~

**Comment by MrGTout** [comment]
什么叫做我要的issues

**Comment by 3TUSK** [comment]
@MrGTout 只是说说而已...

**Comment by panda2134** [comment]
什么鬼。。。

**Comment by 3TUSK** [comment]
没什么特定的鬼…

**Comment by Glease** [comment]
算了，我正在尝试淡出……至少是1个月内

--- Original Message ---

**Comment by 3TUSK** [comment]
Best Wishes
Sent by 3TUSK

**Comment by panda2134** [comment]
?

**Comment by Glease** [comment]
Ah, don't worry. 个人原因，最近特别忙。仅此而已。

--- Original Message ---

**Comment by KaedeLen** [comment]
同意
全是炒冷饭毫无意义

**Comment by 3TUSK** [comment]
> ~~@elctove 说的就是你~~

**Comment by MrGTout** [comment]
没错，说的就是你233

**Comment by Glease** [comment]
噫噫噫噫噫噫噫噫噫噫嘻

--- Original Message ---

**Comment by KaedeLen** [comment]
噫我又没跟着他们水分类啊

**Comment by panda2134** [comment]
@elctove 就是你+1

**Comment by 3TUSK** [comment]
显然水贴似乎少了很多，关了关了

**Comment by Glease** [comment]
wtf... 我觉得管理人员甚至根本什么话都没说。。。

--- Original Message ---
