### ISSUE TITLE
Repo里的各文件中的网址均未被正确链接

### ISSUE THREAD

**Issue by GWYOG** [MCIndustrial2Bar/MCIC2BAR#2]
RT，比如这个链接
`[http://tieba.baidu.com/p/2678094285]()` 不应该写成下面这个形式吗？
`[http://tieba.baidu.com/p/2678094285](http://tieba.baidu.com/p/2678094285)`

**Comment by Glease** [comment]
well... 我是离线编辑的，理论上其实什么都不用加就可以显示链接，MarkdownPad2里必须加这么一个奇怪的语法他才肯显示<a>标签。总之这就是个workaround，不要在意。

**Comment by Glease** [comment]
好吧，是我昏头了，md的链接写法记反了_(:_」∠)_回去改

**Comment by Glease** [comment]
Closed via #4
