### ISSUE TITLE
关于语音高等级发帖机的问题

### ISSUE THREAD

**Issue by ghost** [MCIndustrial2Bar/MCIC2BAR#24]
最近吧里出现了诸如@龙族心云，@凶僦画家，@瞬间永恒jelly，@闲着没事蛋疼22 等高等级（8、9级）发帖机，利用关键字在贴吧中通过语音传播私人信息，影响到了本吧吧友的正常讨论与浏览。鄙人经过对本吧吧友发帖方式的初步考察，发现使用语音发帖的人微乎其微，请问吧务团队能否禁止语音发帖，以减少这些高等级发帖机数量；如果不能的话，能否将这些人限制发帖。谢谢。🙂
                                                                                                                             来自mc工业2吧吧友 tslabc
                                                                                                                                    Sent from windstories

**Comment by Glease** [comment]
后台没有禁止语音的功能，百度也不会允许有这样的功能，目前只能是有一个查封一个了。本人在外面，暂时不便操作，已转发至吧务群请求协助。

--- Original Message ---

**Comment by ghost** [comment]
感谢负责的吧务组的回复，那我是不是应该关闭这个issue？

**Comment by Glease** [comment]
先丢着，等处理完了再关

--- Original Message ---
