### ISSUE TITLE
新吧规意见

### ISSUE THREAD

**Issue by KaedeLen** [MCIndustrial2Bar/MCIC2BAR#5]
ID：凯迪奇
1.第0章2条和13条与第4章6条内容重复（因为很重要所以说三遍不是这么玩的啊喂= =
2.第1章8条和第3章5条重复
3.第8章服务器帖发布人建议加一个服主/OP委托人（比如我这样的
4.第10章标题过于狭义
5.相关连接里mcmod写中文mcmod百科更好吧

**Comment by KaedeLen** [comment]
注明：所看版本为3.0.0

**Comment by 3TUSK** [comment]
@elctove 看文件标题写着**Draft**（草稿）
Something added: 
1. 0章是更新日志（喷）
2. 关于禁止求服务器+无脑伸手那个的确重复了...
3. 改成“引战相关定义及解释”如何
4. mcmod百科这个用法一般不会有歧义吧？

**Comment by Glease** [comment]
Closed via 5a685a0cdf671843dcd3569da0fbf7558ae8cd4e
