### ISSUE TITLE
关于以“大新闻”水贴的处理方式

### ISSUE THREAD

**Issue by Glease** [MCIndustrial2Bar/MCIC2BAR#9]
现阶段贴吧有大量以大新闻水贴的，内容多为名人八卦，实在是无聊，但也存在部分有价值的。提议禁止八卦。对于其他允许发布的贴子，若是关于同一内容的，则同时均只允许存在一个。

**Comment by Ahrwing** [comment]
我们需要更多的海绵！

**Comment by 3TUSK** [comment]
以及更多的水泵。

**Comment by Glease** [comment]
Closed via #11
